### PR TITLE
[PDB-1427] Default date formats in dashboard and PIR are not same

### PR DESCRIPTION
**Pull request by SergeyTravin**
@mdamour1976, @rfellows could you review it please?
It should be merged after
https://github.com/pentaho/pentaho-metadata/pull/84

Thanks!

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@pedrofvteixeira, @pamval Could you start wingman please?

**Comment by pedrofvteixeira** [comment]
[wingman](http://10.100.11.222:8080/job/wingman-ant/449)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  build-res/subfloor-gwt.xml
  build.properties
  ivy.xml
  src/org/pentaho/chart/ChartBeanFactory.java
  test-src/org/pentaho/chart/ChartBeanFactoryTest.java










Unit test coverage change:
============
org.pentaho.chart.data.NamedValue:
 * linePercentCoverage :46.15%
 * methodPercentCoverage :42.86%
 * complexityPercentCoverage :42.86%
 * instructionPercentCoverage :53.33%
    
org.pentaho.chart.data.MultiSeriesDataModel.DomainData:
 * linePercentCoverage :33.33%
 * methodPercentCoverage :20.00%
 * complexityPercentCoverage :20.00%
 * instructionPercentCoverage :36.00%
    
org.pentaho.chart.data.NamedValuesDataModel:
 * branchPercentCoverage :83.33%
 * linePercentCoverage :76.47%
 * methodPercentCoverage :60.00%
 * complexityPercentCoverage :62.50%
 * instructionPercentCoverage :86.44%
    
org.pentaho.chart.ChartBeanFactory:
 * branchPercentCoverage :14.29%
 * linePercentCoverage :23.86%
 * methodPercentCoverage :25.00%
 * complexityPercentCoverage :7.59%
 * instructionPercentCoverage :23.99%
    
org.pentaho.chart.data.MultiSeriesDataModel:
 * branchPercentCoverage :37.50%
 * linePercentCoverage :53.23%
 * methodPercentCoverage :62.50%
 * complexityPercentCoverage :33.33%
 * instructionPercentCoverage :51.08%
    
org.pentaho.chart.data.MultiSeriesDataModel.SeriesData:
 * linePercentCoverage :44.44%
 * methodPercentCoverage :40.00%
 * complexityPercentCoverage :40.00%
 * instructionPercentCoverage :48.00%
    
Integration test coverage change:
============
org.pentaho.chart.ChartBeanFactory:
 * instructionPercentCoverageChange : +0.76%
 * branchPercentCoverageChange : +0.36%
 * linePercentCoverageChange : +1.30%
 * complexityPercentCoverageChange : +1.98%
 * methodPercentCoverageChange : +6.25%

**Comment by SergeyTravin** [comment]
@rfellows, Could you review it please? The wingman did not found any checkstyle violations or regression of test coverage. Thanks!

**Comment by SergeyTravin** [comment]
@kolinus,  @akhayrutdinov  could you review it please? The wingman did not found any checkstyle violations or regression of test coverage. Thanks!

**Pull request merged**
